//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XPO_Project.Database
{

    [NonPersistent]
    public partial class GetGroupQuestionsResult
    {
        public string ID { get; set; }
        public string GroupID { get; set; }
        public string QuestionText { get; set; }
        public string LOVType { get; set; }
        public long AnswerObject { get; set; }
        public long AnswerAttribute { get; set; }
        public bool IsFreeText { get; set; }
        public string AnswerYesValueCriteria { get; set; }
        public DateTime CREATION_DATETIME { get; set; }
        public string CREATED_BY { get; set; }
        public DateTime UPDATE_DATETIME { get; set; }
        public string UPDATED_BY { get; set; }
        public string DELETED_BY { get; set; }
        public DateTime DELETE_DATETIME { get; set; }
    }

}
