//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using System.Linq;
namespace XPO_Project.Database
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecGetGroupQuestions(Session session)
        {
            return session.ExecuteSproc("GetGroupQuestions");
        }
        public static System.Collections.Generic.ICollection<GetGroupQuestionsResult> ExecGetGroupQuestionsIntoObjects(Session session)
        {
            return session.GetObjectsFromSproc<GetGroupQuestionsResult>("GetGroupQuestions").ToList();
        }
        public static XPDataView ExecGetGroupQuestionsIntoDataView(Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetGroupQuestions");
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(GetGroupQuestionsResult)), sprocData);
        }
        public static void ExecGetGroupQuestionsIntoDataView(XPDataView dataView, Session session)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("GetGroupQuestions");
            dataView.PopulateProperties(session.GetClassInfo(typeof(GetGroupQuestionsResult)));
            dataView.LoadData(sprocData);
        }
    }
}
